# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18

    steps:
      - checkout
      - run: cd src && npm install
      - run: cd src && npm test
      - run: cd src && npm eslint

workflows:
  version: 1
  all_jobs:
      jobs:
          - build