# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18

    steps:
      - checkout
      - run: cd src && npm install
      - save_cache:
          key: myapp-{{ checksum  "package.json" }}
          paths:
            - NodeJs-Express-Example/src/node_modules
      #- run: cd src && npm test
      #- run: cd src && npm run eslint

  test:
    docker:
      - image: circleci/node:12.18

    steps:
      - checkout
      - restore_cache:
          keys: myapp-{ checksum  "/src/package.json" }}
      - run: cd src && npm test
      - run: cd src && npm run eslint

workflows:
  version: 2
  all_jobs:
    jobs:
      - build
      - test:
          requires:
            - build